/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMaintenanceRouteRouteImport } from './routes/_app/maintenance/route'
import { Route as AppInventoryRouteRouteImport } from './routes/_app/inventory/route'
import { Route as AppVehiclesVehicleIdRouteImport } from './routes/_app/vehicles/$vehicleId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRouteRoute = AppMaintenanceRouteRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRouteRoute = AppInventoryRouteRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesVehicleIdRoute = AppVehiclesVehicleIdRouteImport.update({
  id: '/vehicles/$vehicleId',
  path: '/vehicles/$vehicleId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/inventory': typeof AppInventoryRouteRoute
  '/maintenance': typeof AppMaintenanceRouteRoute
  '/vehicles/$vehicleId': typeof AppVehiclesVehicleIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/inventory': typeof AppInventoryRouteRoute
  '/maintenance': typeof AppMaintenanceRouteRoute
  '/': typeof AppIndexRoute
  '/vehicles/$vehicleId': typeof AppVehiclesVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/inventory': typeof AppInventoryRouteRoute
  '/_app/maintenance': typeof AppMaintenanceRouteRoute
  '/_app/': typeof AppIndexRoute
  '/_app/vehicles/$vehicleId': typeof AppVehiclesVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/inventory' | '/maintenance' | '/vehicles/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/inventory' | '/maintenance' | '/' | '/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/inventory'
    | '/_app/maintenance'
    | '/_app/'
    | '/_app/vehicles/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicles/$vehicleId': {
      id: '/_app/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof AppVehiclesVehicleIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInventoryRouteRoute: typeof AppInventoryRouteRoute
  AppMaintenanceRouteRoute: typeof AppMaintenanceRouteRoute
  AppIndexRoute: typeof AppIndexRoute
  AppVehiclesVehicleIdRoute: typeof AppVehiclesVehicleIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInventoryRouteRoute: AppInventoryRouteRoute,
  AppMaintenanceRouteRoute: AppMaintenanceRouteRoute,
  AppIndexRoute: AppIndexRoute,
  AppVehiclesVehicleIdRoute: AppVehiclesVehicleIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
